[project]
name = "terraform-provider-ansible"
version = "0.1.0"
requires-python = ">=3.13.12"
dependencies = [
    "ansible>=13.3.0",
    "ansible-lint>=26.1.1",
    "ansible-navigator>=26.1.2",
]
[tool.uv]
required-version = ">=0.10.2"
