[project]
name = "terraform-provider-ansible-example-proxmox"
version = "0.1.0"
requires-python = ">=3.13.9"
dependencies = [
    "ansible-navigator>=25.11.0",
]
[tool.uv]
required-version = ">=0.9.10"
